pgharts/trusty-cms

.travis.yml
These two lines will make Travis CI build a lot faster so less waiting and wondering. :+1:
=> Updated .travis.yml file to speed up build times

Gemfile.lock, config/initializers/trusty_cms_config.rb, lib/login_system.rb, lib/trusty_cms.rb
Delivers: https://github.com/pgharts/trusty-cms/issues/148
Moves Trusty-CMS to version 2.0.2.
=> See bugzid: 3202 - Resolve 500 error on choosing Remember Me at Login

Gemfile.lock, app/controllers/admin/password_resets_controller.rb, app/mailers/password_mailer.rb, app/views/admin/password_resets/edit.html.haml, app/views/admin/password_resets/new.html.haml, app/views/password_mailer/password_reset.html.haml, lib/trusty_cms.rb
Delivered: https://pct.fogbugz.com/f/cases/651/
=> See bugzid: Styling CMS forgot password functionality

app/controllers/application_controller.rb
=> Set default mailer urls based on request.host

.codeclimate.yml, Gemfile.lock, app/controllers/admin/pages_controller.rb, lib/trusty_cms.rb
=> See Issue: 142 - Creating a page with a slug that already exists displays ugly error message

app/models/page.rb, db/migrate/20161027141250_add_position_to_pages.rb, db/schema.rb
Delivers: https://pct.fogbugz.com/f/cases/3650/TrustyCMS-Absorb-Reorder-Extension
=> See bugzid: 3650 - TrustyCMS: Absorb Reorder Extension

app/helpers/application_helper.rb
=> See Issue - 149 - Fix asset path for avatar image

Gemfile.lock, app/helpers/application_helper.rb, lib/login_system.rb, lib/trusty_cms.rb
Fixes: https://github.com/pgharts/trusty-cms/issues/149
Delivers: Bugzid: 3758
=> Fix permissions for unsigned in users and default gravatar image

Gemfile.lock, app/models/page.rb, lib/trusty_cms.rb
Delivers: https://pct.fogbugz.com/f/cases/4197/MySQL-server-version-for-the-right-syntax-to-use-near-virtual-DESC-title-ASC
=> See bugzid: 4197 - MySQL error | near virtual DESC, title ASC | Register version 3.0.6

lib/trusty_cms/admin_ui.rb
Closes https://github.com/pgharts/trusty-cms/issues/225
=> Issue 225 - DEPRECATION WARNING: constant ::Fixnum is deprecated

app/models/page.rb
Resolves: https://github.com/pgharts/trusty-cms/issues/215
=> Issue #215 - Resolve DEPRECATION WARNING: #tables currently returns both tables and views

app/controllers/admin/pages_controller.rb, app/views/layouts/application.html.haml
Updating the relative url root so there is no error in the view
Permit all the params so Page can access individual preview pages.
=> Bugz 1756 preview button

Gemfile.lock, app/controllers/admin/page_fields_controller.rb, lib/trusty_cms.rb
Updating model variable to model.attributes and passing attributes instead of PageField.new
=> BugzID: 4689 - Prod Meta Description

Gemfile.lock, app/models/standard_tags.rb, lib/trusty_cms.rb
=> Resolves Issue #273 - Radius tag <r:children:each> is not working

Gemfile.lock, app/views/admin/pages/_node.html.haml, lib/trusty_cms.rb
=> Closes Issue #295 - Restrict designers from deleting pages

Gemfile.lock, app/controllers/social_mailer_controller.rb, app/views/rad_social_mailer/social_mail_form.html.haml, app/views/widget/_email_form.html.haml, lib/trusty_cms.rb
Update to v3 for the email and add action emailSeats for tracking in captcha admin
Updated version to 3.6.1 from 3.6.0
=> BugzID: 5614 - Update recaptcha for rad social

app/views/admin/sites/index.haml
this might be helpful
Closes #267
=> BugzID: 5933 - Prompt to delete a site

vendor/extensions/clipped-extension/lib/asset_tags.rb
Flash no longer exists. Remove!
Closes #277
=> BugzID: 5932 - Deprecate the flash asset plugin

Gemfile.lock, app/helpers/application_helper.rb, app/models/asset_type.rb, app/models/page.rb, app/models/standard_tags.rb, app/models/trusty_cms/page_response_cache_director.rb, config/application.rb, lib/configuration_extensions/configuration_extensions.rb, lib/trusty_cms.rb, spec/dummy/config/application.rb, vendor/extensions/clipped-extension/lib/asset_tags.rb
This version will also bundle in all of the error message changes @fitzgerald made.
=> Register trusty-cms 3.8.4 and remove a lot of TODOs

app/assets/stylesheets/admin/main.scss
=> Change use back to import

app/assets/stylesheets/admin/partials/_forms.scss, app/views/devise/passwords/new.html.haml
Require an email address on reset password
Update styling of error class
=> Email required for password reset

app/views/admin/layouts/remove.html.haml, app/views/admin/snippets/remove.html.haml, config/locales/en.yml
Also, add tablesaw class to table
=> BugzID: 6123 - Add locales for snippets to fix button

app/assets/stylesheets/admin/partials/_content.scss
Removed the padding from the main content so the width isn't going over the screen size
=> Edge bug - Scrollbar appears as you type

Gemfile.lock, app/controllers/admin/pages_controller.rb, app/controllers/admin/preferences_controller.rb, app/controllers/admin/resource_controller.rb, app/controllers/admin/users_controller.rb, lib/trusty_cms.rb, lib/trusty_cms/setup.rb
Replaces update_attributes with update
**alias update_attributes update
deprecate update_attributes: "please, use update instead"**
Update trusty version
=> Replaces update_attributes

Gemfile.lock, app/assets/config/trusty-cms/manifest.js, config/initializers/assets.rb, lib/trusty_cms.rb
Adds a manifest file to the assets/config folder
=> Upgrade to sprockets manifest file

.codeclimate.yml
Bumped the RuboCop channel in .codeclimate.yml from 1-9-1 -> 1-22-2
=> BugzID: 6777 - unknown Ruby version

Gemfile.lock, app/controllers/admin/assets_controller.rb, app/models/asset.rb, lib/trusty_cms.rb
That create method is getting really unwieldy. Would like to look into cleaning it up a bit.
=> Up file size validation

lib/trusty_cms/version.rb
Updates `trusty-cms` to version `7.0.4`.
=> Update Version to 7.0.4
