pgharts/trusty-cms

- Gemfile.lock
- lib/ostruct.rb
- lib/trusty_cms.rb
With the Ruby 2.3.1 upgrade, the class OpenStruct was failing because the hash that returns a new Response.new is not setting the default instance variables anymore. Just calling key? doesn't trigger the setting of the default value:
Ruby 2.2: https://github.com/ruby/ruby/blob/ruby_2_2/lib/ostruct.rb#L184-L186
Ruby 2.3: https://github.com/ruby/ruby/blob/trunk/lib/ostruct.rb#L204-L206
This forced me to patch OpenStruct to use the Ruby 2.2 behavior. Tests are passing and it runs smoothly on the Trust's websites.
> Register 2.0.23 to make TrustyCMS compatible with Ruby 2.3.1

- Gemfile.lock
- app/models/haml_filter.rb
- app/models/rails_page.rb
- app/views/layouts/trusty.html.haml
- lib/trusty_cms.rb
- vendor/extensions/layouts-extension/layouts_extension.rb
- vendor/extensions/layouts-extension/lib/haml_layouts/models/layout.rb
- vendor/extensions/layouts-extension/lib/haml_layouts/models/page.rb
- vendor/extensions/layouts-extension/lib/layouts/engine.rb
- vendor/extensions/layouts-extension/lib/share_layouts/controllers/action_controller.rb
- vendor/extensions/layouts-extension/lib/share_layouts/helpers/action_view.rb
- vendor/extensions/layouts-extension/lib/tasks/layouts_extension_tasks.rake
- vendor/extensions/layouts-extension/lib/trusty-layouts-extension.rb
Retires the need to maintain: https://github.com/pgharts/trusty-layouts-extension
> Collapse trusty-layouts-extension into TrustyCMS core

- Gemfile.lock
- app/controllers/admin/snippets_controller.rb
- app/helpers/admin/snippets_helper.rb
- app/views/snippets/_form.html.haml
- app/views/snippets/_popups.html.haml
- app/views/snippets/edit.html.haml
- app/views/snippets/index.html.haml
- app/views/snippets/new.html.haml
- app/views/snippets/remove.html.haml
- config/initializers/trusty_cms_config.rb
- config/routes.rb
- lib/tasks/snippets_extension_tasks.rake
- lib/trusty_cms.rb
* Collapse the trusty-snippets-extension modules into TrustyCMS core. This retires the snippets extension. 
* Register TrustyCMS 3.1.7
> Collapse trusty-snippets-extension into TrustyCMS

- Gemfile.lock
- app/models/site.rb
- trusty_cms.gemspec
- Per the bullet gem, removed the N+1 query that was being executed when loading a homepage after locating a site
- Add in sass-rails as a holdover for removing compass
> Add in sass-rails as a dependency, eager load homepage when site is detected

- app/controllers/admin/password_resets_controller.rb
- app/views/admin/password_resets/new.html.haml
- app/views/admin/welcome/login.html.haml
* Remove Powered by TrustyCMS
* Make the forgot password message more generic and helpful -- whether they are an user or not
> Rapid 7 Security Updates: Round 1

- Gemfile.lock
- app/controllers/admin/assets_controller.rb
- lib/trusty_cms.rb
Mode no longer needs to be a hash and File.write needs to use URI.open
> Ruby 3 Upgrade - Update to URI.open

- Gemfile.lock
- app/assets/config/trusty-cms-manifest.js
- app/assets/config/trusty-cms/manifest.js
- lib/trusty_cms.rb
Going forward - if the rails app using this engine is using precompiled assets - they will need to add trusty-cms-manifest.js to the config/initializers/assets.rb under precompile.
> Change trusty-cms manifest to engine-name-manifest

- Gemfile.lock
- lib/trusty_cms.rb
Adds haml-lint config and bumps `rspec-rails` 5.0.2 -> 5.1.0
> Bump gem version -> 5.0.6

- app/models/asset.rb
The thumbnails in the asset table were not rendering properly because the method checks if original is being passed through and renders the "original" asset instead of the thumbnail size.
I want the original asset to render but I want it to be thumbnail sized but in other times when we are trying to generate original images, we want those to show properly as well.
So I needed to make a new check for both original and if the asset key contains culturaldistrict.
> This is a result of the paperclip to active storage migration.

- lib/generators/instance/templates/instance_environment.rb
- lib/generators/trusty_cms/templates/application.rb.erb
These TODOs are from pretty far back, but they seem to mirror a configuration that we're using throughout our app, in which:
- Middleware for Rack::Cache is configured
- an `insert_before` call is used to have Rack::ConditionalGet fire before Rack::Cache.
This same configuration is also used in CD and Festivity's application.rb, so unless this is causing a specific issue, I think these are fine to leave as they are.
> BugzID: 7382 - Review TODOs in lib/

- app/views/admin/users/index.html.haml
- lib/trusty_cms.rb
- lib/trusty_cms/admin_ui.rb
This pr uses Devise's Trackable module to list the last signed in date for the users in TrustyCMS. This is a first step towards building a system to alert us if a user has not used the CMS in some time to determine if we need to remove their access to it.
> BugzID: 7423 - Add last_sign_in to users table in admin

- app/views/admin/preferences/edit.html.haml
- lib/trusty_cms.rb
This pr fixes the broken admin/preferences resource by removing a render call for the avatar partial that was deleted in an earlier version.
> BugzID: 7442 - Remove broken render call to avatar

- config/initializers/trusty_cms_config.rb
- lib/trusty_cms.rb
sidekiq has been giving warnings that the following constants are autloaded during initialization and that doing so is deprecated: `TrustyCms::Config, Admin, Admin::RegionsHelper, ApplicationHelper, ApplicationController, Admin::ResourceHelper, Admin::ResourceController, Admin::LayoutsHelper, Admin::LayoutsController, MultiSite::SiteChooserHelper, Admin::SnippetsController, ShareLayouts, ShareLayouts::Controllers, ShareLayouts::Controllers::ActionController, SiteHelper, SiteController, Extensions, Extensions::SiteControllerExtensions, TrustyCms::Taggable, StandardTags, DeprecatedTags, Page, PageAssetAssociations, MultiSite::PageExtensions, CulturaldistrictApp, ShoppingCartMustNotBeEmptyFilter, ShoppingCartMustBeEmptyFilter, CulturaldistrictApp::ApplicationControllerExtensions, …
> BugzID: 7499 - Quiet deprecation warning in Sidekiq

- lib/generators/language_extension/templates/available_tags.yml
I can't find `unless_url` in StandardTags anywhere. It might have been deleted in an earlier jenga pr. This pr removes the description from AvailableTags.
> BugzID: 7530 - Jenga: unless_url

- Gemfile.lock
- config/initializers/zeitwerk.rb
- lib/trusty_cms.rb
Add zeitwerk name inflection updates so that apps loading the engine won't fail on extensions.
> TrustyCMS v6.0.1 - Name Inflection updates

- Gemfile.lock
- app/models/trusty_cms/config.rb
- lib/trusty_cms.rb
in order to pass variables through
> Turns out we need to cache TrustyCms::Config

- Gemfile.lock
- app/controllers/admin/pages_controller.rb
- lib/trusty_cms.rb
- lib/trusty_cms/task_support.rb
> Remove .html.haml from render directive

- Gemfile.lock
- app/models/asset.rb
- config/initializers/zeitwerk.rb
- lib/trusty_cms.rb
- trusty_cms.gemspec
- vendor/extensions/clipped-extension/lib/clipped/engine.rb
No need to depend on an external gem to generate a UUID. A zeitwerk problem arose generating one from the gem.
> Remove uuidtools in favor of self generated UUID

- app/models/user.rb
- app/views/admin/layouts/_site_chooser.html.haml
The user should not see the site chooser if they are only scoped to one site. Adds a scoped? method that returns true if there is a site id and false if no site id exists.
> Hide Site Chooser if user is scoped to site

- app/models/file_not_found_page.rb
- lib/trusty_cms.rb
The FileNotFound page error was fixed (in which the status was returning a 200 rather than a 404), but the cache heads were being set to private. This pr changes the value of the override method `#cache?` from 'false' to 'true', and defines a cache_timeout method.
> #4858 - set cache?=true, cache_timeout

- app/assets/javascripts/admin/assets.js
- app/controllers/admin/assets_controller.rb
- app/controllers/admin/pages_controller.rb
- app/views/admin/pages/_asset_popups.html.haml
- lib/trusty_cms.rb
- Push assets to the search partial from the asset popup << add ransack term ivar to the edit controller, and I needed to add an edit controller to introduce some functionality to it. 
- Reintroduce autocomplete using the ransack params - I realized that you can't search in the popup without it. Pressing enter just redirects to assets tab page. Not helpful. 
- Add a pause before the search starts on keyup to avoid mixups in search. I noticed that in testing this - if i was typing out my search sometimes what I type was out of order in the search action. For example, searching "Benedum" I would see
cache: [GET /admin/assets?search[title_cont]=bene&pp=50] miss
cache: [GET /admin/assets?search[title_cont]=benedum&pp=50] miss
cache: [GET /admin/assets?search[title_cont]=ben&pp=50] miss …
> Fix assets breaking on pages/edit

- Gemfile.lock
- app/controllers/admin/pages_controller.rb
- lib/trusty_cms.rb
The pages controller didn't have access to the term object therefore it was falling over on creating a new page. When I added it, everything worked successfully.
> Fix ransack error on creating pages

- app/views/admin/pages/_fields.html.haml
- lib/trusty_cms/version.rb
This pr increases the size of the 'Page Title' field in Trusty to accomodate > 50 characters via the in-line 'size' attribute.
> #5117 - Set page_title field length to 100

- .circleci/config.yml
- Gemfile.lock
- config/application.rb
- lib/active_record_extensions/active_record_extensions.rb
- lib/trusty_cms/extension_loader.rb
- lib/trusty_cms/initializer.rb
- lib/trusty_cms/version.rb
- spec/dummy/config/application.rb
- vendor/extensions/layouts-extension/layouts_extension.rb
- vendor/extensions/multi-site-extension/lib/multi_site/scoped_validation.rb
- vendor/extensions/multi-site-extension/multi_site_extension.rb
- vendor/extensions/snippets-extension/snippets_extension.rb
- Removes the gem loader for extensions as this has been deprecated for a while
- Rewrites the module MultiSite::ScopedValidation to use prepend methods as this was causing a stack error when making changes and reloading
- Comment out dependency observer. This should no longer be needed for zeitwerk should be autoloading extensions and dependencies. 
- Shows that in the new world, config.to_prepare should be utilized instead of after_initialize. This file makes no difference but when the engine is installed this configuration will be passed on to the app that is installing trusty-cms. The .to_prepare will direct the app to reload what is inside this block, so instead of using the dependency observer, the app will deactivate and reactive extensions inside this block instead.
- Register …
> v6.3: Update for full compatibility with zeitwerk

- Gemfile.lock
- app/assets/javascripts/admin/custom_file_upload.js
- app/controllers/admin/assets_controller.rb
- app/helpers/admin/references_helper.rb
- app/views/admin/assets/new.html.haml
- lib/trusty_cms/version.rb
Resolves [#2049](https://github.com/pgharts/festivity-site/issues/2049) - The issue here is that the first "input" is blank, since it's a multipart uploader, causing a blank first entry in the array. Ended up adding a reject blank entries here to avoid this on the backend. 
Resolves [#2048](https://github.com/pgharts/festivity-site/issues/2048) - This was a simple 'remove the file extension from the render partial' and I checked the rest of the app and it doesn't seem that we do this anywhere else.
Deprecates the caption input - this is not rendering anywhere.
> TrustyCMS v 7.0.1 - Bug fixes

- app/controllers/admin/configuration_controller.rb
- app/controllers/admin/extensions_controller.rb
- app/controllers/admin/layouts_controller.rb
- app/controllers/admin/sites_controller.rb
- app/controllers/admin/snippets_controller.rb
- app/controllers/admin/users_controller.rb
- app/helpers/admin/users_helper.rb
- app/models/user.rb
- app/views/admin/layouts/_site_chooser.html.haml
- app/views/admin/pages/_fields.html.haml
- app/views/admin/pages/_node.html.haml
- app/views/admin/users/_form.html.haml
- config/locales/en.yml
- lib/login_system.rb
**Refactor:** Alias designer to editor, Add content editor Role, and Enhance Role-Based Validation
This PR includes several updates related to roles and permissions in the application:
**Admin**: Full access to all permissions.
**Editor**: All permissions except user and site management.
**Content Editor**: All permissions except user management, site editing, publishing, and deleting content.
1. Renamed designer to editor:
1. The `designer` role has been aliased to `editor` to better align with the role's purpose.
2. Changes were implemented using `editor?` method for backward compatibility.
2. Added content editor Role:
1. Introduced a new `content editor` role with specific permissions. This already existed in some ways but not properly implemented.
3. Backend Validation for Roles:
1. …
> Add better role support for users

- config/initializers/devise.rb
Updates Devise configuration to update user session timeout from the 30 minute default to 8 hours. This update is intended to fix login issues experienced by PSO users.
[Issue 860: Change timeoutable config to 8 hours](https://github.com/pgharts/trusty-cms/issues/860)
> Update Timeout Configuration from 30 Minute Default to 8 Hours

- Gemfile.lock
- app/assets/config/trusty-cms-manifest.js
- lib/trusty_cms/version.rb
This bugfix aims to resolve the error below by adding the `scheduled_status_validation.js` file to the asset pipeline. This PR also updates the gem version to `7.0.5`.
```
Sprockets::Rails::Helper::AssetNotPrecompiledError: Asset `admin/validations/scheduled_status_validation.js` 
was not declared to be precompiled in production. Declare links to your assets in `app/assets/config/manifest.js`. 
//= link admin/validations/scheduled_status_validation.js and restart your server
```
> Add Scheduled Status Validation JavaScript to Asset Pipeline

- Gemfile
- Gemfile.lock
- app/controllers/admin/pages_controller.rb
- app/controllers/application_controller.rb
- app/models/page.rb
- app/models/page_field.rb
- app/models/page_part.rb
- config/initializers/paper_trail.rb
- config/routes.rb
- db/migrate/20250102212417_create_versions.rb
- db/migrate/20250103191133_create_version_associations.rb
- db/migrate/20250103191134_add_transaction_id_column_to_versions.rb
- lib/trusty_cms/version.rb
This PR introduces the ability to revert to a previous version of a page using the `paper_trail` gem alongside the `paper_trail-association_tracking` plugin. Users can now restore pages to a specific historical state, including associated data, while preserving version history.
- Saves version history for the last five versions of a Page.
- Saves associated `PagePart` and `PageField` objects.
This feature does not save parts of a page that are independently saved, such as Related Sections or Persons. 
[Issue 714: Create a "Version Control" ability for Pages](https://github.com/pgharts/trusty-cms/issues/714)
> Add Page Version Restore Feature

- app/controllers/admin/pages_controller.rb
- app/helpers/admin/pages_helper.rb
- app/models/page.rb
- app/views/admin/pages/_fields.html.haml
- config/locales/en.yml
- lib/trusty_cms/admin_ui.rb
- lib/trusty_cms/version.rb
Add the ability to update the Parent of a Page
- Resolves #858
_You should be able to change the parent of any page in the CMS_
_By clicking page, scrolling to the bottom of the page and choosing the "Parent" dropdown you will see a top level list of parent pages. To help the usability and UX of this feature, I chose to only use the very top level pages. This ensures an easy to read and use drop down. For nested pages, the user will still have to delete and recreate under a different parent._
_We encourage you to keep the code coverage percentage at 80% and above._
If you have a pages_helper.rb for admin/helpers - you will need to copy the new helper method to the file.
> Add the ability to update the Parent of a Page

- Gemfile.lock
- README.md
- app/controllers/page_status_controller.rb
- app/views/layouts/application.html.haml
- lib/trusty_cms/version.rb
This pull request introduces the integration of Google Tag Manager (GTM) into the admin pages of the TrustyCMS application. The primary objective is to monitor the usage frequency of the CKEditor, enabling us to assess monthly load requirements effectively.
Additionally, this update refines the method of accessing the page status refresh token credentials by incorporating the safe navigation operator (&.) and the dig method, thereby enhancing the robustness of credential retrieval and preventing potential errors.
This pull request updates TrustyCMS to version `7.0.12`.
[Issue 6143: Add GTM to /admin pages](https://github.com/pgharts/culturaldistrict.org/issues/6143)
> Implement Google Tag Manager for Admin Page Tracking and Enhance Credential Access Safety

- Gemfile.lock
- app/models/standard_tags.rb
- app/models/status.rb
- config/locales/en_available_tags.yml
- lib/generators/language_extension/templates/available_tags.yml
- lib/trusty_cms/version.rb
This pull request removes the Hidden status option from pages in the CMS. Accompanying this PR are changes made directly to the database updating pages with the Hidden status to utilize the Draft status.
After merging this pull request, run the following SQL statement to update pages with the Hidden status to Draft status on the staging and production databases for Cultural District and Festivity.
```sql
UPDATE pages 
SET status_id = 1 
WHERE status_id = 101;
```
Resolves [Issue 852: Jenga "Hidden" page status](https://github.com/pgharts/trusty-cms/issues/852)
> Remove Hidden Status from Pages

- Gemfile.lock
- app/assets/stylesheets/admin/partials/_table.scss
- app/helpers/admin/node_helper.rb
- app/views/admin/pages/_search_result_node.html.haml
- app/views/admin/pages/search.html.haml
- config/locales/en.yml
- lib/trusty_cms/admin_ui.rb
- lib/trusty_cms/version.rb
This pull request introduces a Path column to the Page Search results, enabling users to quickly identify a page’s location within the page hierarchy.
- **Added a Path column:** Displays the full path of each page in search results for easier navigation.
- **Removed the dropdown function for displaying child pages:** The updated template caused rendering issues, so this functionality was removed.
The Path column was requested to help users locate pages more efficiently.
Resolves [Add Path to Page Search Results](https://github.com/pgharts/trusty-cms/issues/907)
> Add Path Column to Page Search Results

- Gemfile.lock
- config/initializers/devise.rb
- lib/trusty_cms/version.rb
We are attempting to resolve a log out issue. When a user is logged into the Admin pages, opens a new tab, navigates to a non-Admin site and returns to the Admin tab, the user is signed out when they select any button. In this PR, we set `sign_out_all_scopes` to `false` to see if this resolves this issue.
We are skipping a version due to `7.0.15` already being released and removed.
[Issue 736: Include site_id query param in all actions ](https://github.com/pgharts/trusty-cms/issues/736)
> Set sign_out_all_scopes to False

- Gemfile.lock
- README.md
- app/views/admin/pages/_fields.html.haml
- lib/trusty_cms/version.rb
- vendor/extensions/layouts-extension/lib/share_layouts/helpers/action_view.rb
This pull request introduces two key updates:
1. Adds a `missing can_view_drafts?` method, used as an argument in `Page.find_by_path`, enabling appropriate draft visibility logic.
2. Implements a `trusty-no-cache` URL parameter in the **Save and View Draft** feature to ensure fresh content by bypassing both CloudFront and browser-level caching.
> Add Missing can_view_drafts? Argument and Add trusty-no-cache Parameter to Save and View Draft URL

- Gemfile.lock
- app/controllers/admin/pages_controller.rb
- app/helpers/admin/node_helper.rb
- app/helpers/admin/url_helper.rb
- app/models/page.rb
- lib/trusty_cms/version.rb
This PR improves the readability of the `Page.path` method by refactoring it for clarity and simplifying its recursive logic. Additionally, it moves the `format_path` method into the `Admin::UrlHelper` module for better organization and reuse across the codebase.
> Improve Readability of Page.path Method and Move format_path Method to Admin::UrlHelper Module
